   ## Dot Product

Dot product of two arrays. Specifically,

If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).

If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.

If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.

If a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last axis of b:

In [2]:
import numpy as np

In [16]:
import pandas as pd

In [3]:
mat1 = np.random.randint(10,size = (5, 3))
mat1

array([[7, 3, 7],
       [8, 0, 3],
       [6, 5, 8],
       [4, 3, 7],
       [9, 6, 7]])

In [4]:
mat2 = np.random.randint(10,size = (5, 3))
mat2

array([[8, 6, 9],
       [2, 5, 8],
       [2, 2, 2],
       [1, 7, 5],
       [5, 4, 3]])

In [ ]:
# element wise multiplication (Hadamard Mult)

In [6]:
mat1 * mat2

array([[56, 18, 63],
       [16,  0, 24],
       [12, 10, 16],
       [ 4, 21, 35],
       [45, 24, 21]])

In [ ]:
# Dot product

In [7]:
# pay attention to error message

In [8]:
np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [9]:
# ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [ ]:
# if matrix1 is: A, B, C      shape (3 X 3)
             #   D, E, F
             #   G, H, I

# if matrix2 is: J, K,      shape (3 X 2)
             #   L, M, 
             #   N, O, 

# the Dot product would be A*J + B*L + C*N, A*K + B*M + C*O
                        #  D*J + E*L + F*N, D*K + E*M + F*O
    #                      G*J + H*L + I*N, G*K + H*M + I*O   shape (3 X 2)

# resulting size is the outside numbers of the matrices to be multiplied
# inside numbers must match mat1 shape is (3 X 3) and 2 is (3 X 2) the inner 3's match 
#and the outer numbers form the resulting shape
# ValueError: shapes (5,3) and (5,3) inner numbers are 3 and 5 so it won't work without some manipulation

In [10]:
mat1.shape, mat2.T.shape

((5, 3), (3, 5))

In [ ]:
# in the above line the inside values match (3 and 3) and the resulting shape will be 5 X 5
# or 5 rows and 5 cols

In [11]:
mat3 = np.dot(mat1, mat2.T)
mat3

array([[137,  85,  34,  63,  68],
       [ 91,  40,  22,  23,  49],
       [150, 101,  38,  81,  74],
       [113,  79,  28,  60,  53],
       [171, 104,  44,  86,  90]])

In [12]:
mat3.shape

(5, 5)

## Dot Product Example

In [14]:
np.random.seed(0)
#number of jars sold
sales_amounts=np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [20]:
#cerate a days of week list to be used as indx for sales array
days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
cols = ["Almond Butter", "Peanut Butter", "Cashew Butter"]

In [21]:
# create a weekly sales datafram
weekly_sales = pd.DataFrame(sales_amounts, days, cols)
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Monday                12             15              0
Tuesday                3              3              7
Wednesday              9             19             18
Thursday               4              6             12
Friday                 1              6              7

In [22]:
# create prices array
prices = np.array([10, 8, 12])

In [31]:
# create product prices dataframe
product_prices = pd.DataFrame(prices.reshape(1,3),["Price"], cols)
product_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [32]:
total_sales = prices.dot(sales_amounts)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [33]:
# shapes aren't aligned so transpose

In [34]:
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [ ]:
## now I want to add the total_sales as a column

In [35]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Monday                12             15              0
Tuesday                3              3              7
Wednesday              9             19             18
Thursday               4              6             12
Friday                 1              6              7

In [36]:
weekly_sales.shape, total_sales.shape

((5, 3), (5,))

In [37]:
total_sales

array([240, 138, 458, 232, 142])

In [38]:
weekly_sales["Totals"] = total_sales

In [39]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Totals
Monday                12             15              0     240
Tuesday                3              3              7     138
Wednesday              9             19             18     458
Thursday               4              6             12     232
Friday                 1              6              7     142

In [41]:
product_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

## Sorting Arrays

In [43]:
random_array  = np.random.randint(20, size = (5,5))
random_array

array([[14, 17,  5, 13,  8],
       [ 9, 19, 16, 19,  5],
       [15, 15,  0, 18,  3],
       [17, 19, 19, 19, 14],
       [ 7,  0,  1,  9,  0]])

### np.sort()
**Signature:** np.sort(a, axis=-1, kind=None, order=None)\
**Docstring:** \
Return a sorted copy of an array.

In [44]:
np.sort(random_array)

array([[ 5,  8, 13, 14, 17],
       [ 5,  9, 16, 19, 19],
       [ 0,  3, 15, 15, 18],
       [14, 17, 19, 19, 19],
       [ 0,  0,  1,  7,  9]])

### np.argsort
**Signature:** np.argsort(a, axis=-1, kind=None, order=None)\
**Docstring:** \
Returns the indices that would sort an array.

In [45]:
np.argsort(random_array)

array([[2, 4, 3, 0, 1],
       [4, 0, 2, 1, 3],
       [2, 4, 0, 1, 3],
       [4, 0, 1, 2, 3],
       [1, 4, 2, 0, 3]], dtype=int64)

In [48]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

### np.argmin()
***Signature:*** np.argmin(a, axis=None, out=None, *, keepdims=<no value>)\
***Docstring:*** \
Returns the indices of the minimum values along an axis.

In [49]:
np.argmin(a1)

0

In [53]:
np.argmax(random_array, axis =0)

array([3, 1, 3, 1, 3], dtype=int64)

In [ ]:
# the above returns the largest value along the columns or vertically 

In [51]:
random_array

array([[14, 17,  5, 13,  8],
       [ 9, 19, 16, 19,  5],
       [15, 15,  0, 18,  3],
       [17, 19, 19, 19, 14],
       [ 7,  0,  1,  9,  0]])

In [56]:
# 3 is 15, 1 is 19, 3 is 19 etc

In [57]:
#this will return the rows
np.argmax(random_array, axis=1)

array([1, 1, 3, 1, 3], dtype=int64)

In [58]:
random_array

array([[14, 17,  5, 13,  8],
       [ 9, 19, 16, 19,  5],
       [15, 15,  0, 18,  3],
       [17, 19, 19, 19, 14],
       [ 7,  0,  1,  9,  0]])

## Practical Example

<img src ="numpy-images/panda.png"/>

In [62]:
# turn an image into a numpy array

In [63]:
from matplotlib.image import imread as im 

### imread()
***Signature:*** im(fname, format=None)\
***Docstring:*** \
Read an image from a file into an array.

In [64]:
panda = im("numpy-images/panda.png")

In [65]:
print(type(panda))

<class 'numpy.ndarray'>


In [66]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [69]:
panda.ndim

3

In [70]:
panda.size

24465000

In [71]:
panda.shape

(2330, 3500, 3)

In [68]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.