In [4]:
#import numpy
import numpy as np

## Datatypes and Attributes

In [2]:
#nupy's main type is ndarray

In [50]:
a1 = np.array([1,2,3])

In [4]:
##check type
type(a1)

numpy.ndarray

In [51]:
## create more sample arrays with various dimensions

a2 = np.array([[1, 2.0, 3.3],
                [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [52]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [53]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [11]:
# use ndim to check dimensions of an array
a3.ndim

3

In [12]:
# use dtype to see the datatype
a2.dtype

dtype('float64')

In [13]:
# notice that because there are floats and ints in a2 the type defaults to float

In [14]:
# size shows the number of elements

a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
# create a DataFrame from an ndarray

import pandas as pd

In [16]:
df = pd.DataFrame(a2)

In [17]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating Arrays

### creating prefilled arrays

In [23]:
# you can create an array with all zeros
#zeros(shape, dtype=float, order='C', *, like=None)

zeros = np.zeros((4,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
#ditto for ones
# np.ones(shape, dtype=None, order='C', *, like=None)

ones = np.ones((3,5))
ones


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
#you can also create an array based on a range
#arange([start,] stop[, step,], dtype=None, *, like=None)

range_o_nums = np.arange(0, 101, 6)
range_o_nums

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96])

In [41]:
range_o_nums.shape

(17,)

In [42]:
## I want to reshape this array but there's an odd number. Lets add one
new_arr = np.append(range_o_nums, 100)

In [41]:
new_arr

array([  0,   6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72,
        78,  84,  90,  96, 100])

In [42]:
new_arr.shape

(18,)

In [44]:
reshaped_arr = np.reshape(new_arr, (3,6))

In [45]:
reshaped_arr

array([[  0,   6,  12,  18,  24,  30],
       [ 36,  42,  48,  54,  60,  66],
       [ 72,  78,  84,  90,  96, 100]])

In [23]:
# you can also use randoms
#randint(low, high=None, size=None, dtype=int)
random_arr = np.random.randint(0, 100, size=(3,5))

random_arr

array([[44, 44, 19, 16, 98],
       [39, 50, 65, 35, 45],
       [52,  1, 18, 63,  2]])

In [24]:
#random(size=None)
new_rand = np.random.random((5,3))

In [25]:
new_rand

array([[0.11621659, 0.08600072, 0.66562461],
       [0.32957136, 0.36165062, 0.526111  ],
       [0.42472996, 0.81978073, 0.57128475],
       [0.88111074, 0.80060352, 0.34992523],
       [0.77273869, 0.89649666, 0.78573034]])

In [26]:
# rand(d0, d1, ..., dn)
rando = np.random.rand(5,3)

In [27]:
rando

array([[0.28340737, 0.88190845, 0.54538261],
       [0.82802212, 0.23369201, 0.20287765],
       [0.95833623, 0.76615276, 0.18825085],
       [0.46938131, 0.50253021, 0.1723629 ],
       [0.29840685, 0.26880733, 0.88689813]])

In [8]:
#psuedo random numbers
#seed(self, seed=None)
# Reseed a legacy MT19937 BitGenerator
seed = np.random.seed(3)

In [1]:
#random seed helps generate the same random results eachtime


In [28]:
#for example I'll run a random array
new_rand = np.random.random((5,3))
new_rand

array([[0.50325529, 0.57223762, 0.34241958],
       [0.60964572, 0.12061737, 0.03891809],
       [0.99997546, 0.26794775, 0.25720637],
       [0.27664155, 0.25174151, 0.89773703],
       [0.83524631, 0.14631622, 0.99544318]])

In [29]:
# once more
new_rand

array([[0.50325529, 0.57223762, 0.34241958],
       [0.60964572, 0.12061737, 0.03891809],
       [0.99997546, 0.26794775, 0.25720637],
       [0.27664155, 0.25174151, 0.89773703],
       [0.83524631, 0.14631622, 0.99544318]])

In [30]:
#these are the same because the random seed
new_rand

array([[0.50325529, 0.57223762, 0.34241958],
       [0.60964572, 0.12061737, 0.03891809],
       [0.99997546, 0.26794775, 0.25720637],
       [0.27664155, 0.25174151, 0.89773703],
       [0.83524631, 0.14631622, 0.99544318]])

In [31]:
#to change it I need to create a new instance
new_rand = np.random.random((1,3))
new_rand

array([[0.35572909, 0.54713075, 0.49181555]])

In [37]:
new_rando = np.random.random((10,10))
new_rando

array([[0.12965838, 0.86005346, 0.2183979 , 0.82433139, 0.99828312,
        0.99129572, 0.15766976, 0.47066598, 0.70743151, 0.34000592],
       [0.69674999, 0.74840772, 0.81703536, 0.84772195, 0.08157105,
        0.30768373, 0.56098627, 0.91986042, 0.09488134, 0.40589898],
       [0.53846369, 0.64957325, 0.30996164, 0.84135377, 0.49666496,
        0.7037397 , 0.67888305, 0.62340361, 0.9978124 , 0.15964715],
       [0.81954209, 0.3024983 , 0.10592173, 0.28630413, 0.71360454,
        0.2384363 , 0.69766567, 0.02552787, 0.92849884, 0.36307628],
       [0.80005733, 0.7195558 , 0.60249053, 0.23146103, 0.44358768,
        0.64307498, 0.78238398, 0.79376227, 0.38092887, 0.40791699],
       [0.10565921, 0.43900271, 0.85423064, 0.96942917, 0.72015124,
        0.41009134, 0.13917651, 0.02209581, 0.22237632, 0.35674568],
       [0.78275753, 0.44940119, 0.47693177, 0.51628575, 0.36848027,
        0.26242735, 0.80282797, 0.9007708 , 0.36108377, 0.88406467],
       [0.3061273 , 0.28368945, 0.2128943

In [46]:
#find unique values
np.unique(reshaped_arr)

array([  0,   6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72,
        78,  84,  90,  96, 100])

In [47]:
mults = np.array([1,1,2,3,3,4,5,5,5,6,7,7,])

In [48]:
np.unique(mults)

array([1, 2, 3, 4, 5, 6, 7])

In [49]:
#viewing arrays and matricies

In [54]:
#view first element
a1[0]

1

In [55]:
a1

array([1, 2, 3])

In [56]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [57]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [58]:
a2[0]

array([1. , 2. , 3.3])

In [59]:
a3.shape

(2, 3, 3)

In [60]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
a3[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [63]:
a4 = np.random.randint(10,size=(2,3,4,5))

In [64]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [65]:
a4

array([[[[5, 4, 5, 2, 4],
         [1, 3, 2, 1, 4],
         [5, 8, 3, 1, 2],
         [6, 5, 7, 1, 3]],

        [[9, 3, 5, 0, 7],
         [2, 6, 0, 1, 0],
         [4, 6, 5, 6, 4],
         [9, 7, 0, 4, 2]],

        [[8, 9, 8, 2, 8],
         [8, 4, 8, 0, 4],
         [7, 9, 5, 9, 6],
         [4, 6, 3, 0, 6]]],


       [[[3, 1, 4, 1, 5],
         [1, 8, 9, 3, 0],
         [1, 4, 8, 5, 4],
         [3, 5, 0, 8, 7]],

        [[4, 3, 3, 6, 1],
         [7, 9, 1, 2, 0],
         [7, 1, 5, 2, 2],
         [1, 3, 4, 3, 8]],

        [[0, 6, 8, 3, 9],
         [7, 1, 8, 2, 8],
         [0, 4, 8, 8, 6],
         [4, 3, 0, 4, 0]]]])

In [66]:
a4[0]

array([[[5, 4, 5, 2, 4],
        [1, 3, 2, 1, 4],
        [5, 8, 3, 1, 2],
        [6, 5, 7, 1, 3]],

       [[9, 3, 5, 0, 7],
        [2, 6, 0, 1, 0],
        [4, 6, 5, 6, 4],
        [9, 7, 0, 4, 2]],

       [[8, 9, 8, 2, 8],
        [8, 4, 8, 0, 4],
        [7, 9, 5, 9, 6],
        [4, 6, 3, 0, 6]]])

In [67]:
#get the first four numbers of the innermost arrays
a4[:, :, :, :4]

array([[[[5, 4, 5, 2],
         [1, 3, 2, 1],
         [5, 8, 3, 1],
         [6, 5, 7, 1]],

        [[9, 3, 5, 0],
         [2, 6, 0, 1],
         [4, 6, 5, 6],
         [9, 7, 0, 4]],

        [[8, 9, 8, 2],
         [8, 4, 8, 0],
         [7, 9, 5, 9],
         [4, 6, 3, 0]]],


       [[[3, 1, 4, 1],
         [1, 8, 9, 3],
         [1, 4, 8, 5],
         [3, 5, 0, 8]],

        [[4, 3, 3, 6],
         [7, 9, 1, 2],
         [7, 1, 5, 2],
         [1, 3, 4, 3]],

        [[0, 6, 8, 3],
         [7, 1, 8, 2],
         [0, 4, 8, 8],
         [4, 3, 0, 4]]]])

## Manipulating and Comparing Arrays

### Arithmetic

In [68]:
a1

array([1, 2, 3])

In [73]:
ones = np.ones(3)

In [74]:
ones

array([1., 1., 1.])

In [75]:
#simple addition

a1 + ones

array([2., 3., 4.])

In [76]:
#they have to be the same shape

In [77]:
a1 - ones

array([0., 1., 2.])

In [78]:
a1 * ones

array([1., 2., 3.])

In [82]:
a1

array([1, 2, 3])

In [83]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [79]:
# multiplying a1 by a2
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [ ]:
# a1 is a single row and it multiplies that row by each row on a2
#this is called broadcasting. 
#arrays have to have the same size

In [84]:
a3.shape

(2, 3, 3)

In [85]:
a1.shape

(3,)

In [86]:
a1 * a3

array([[[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]],

       [[10, 22, 36],
        [13, 28, 45],
        [16, 34, 54]]])

In [87]:
a2.shape

(2, 3)

In [88]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [89]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [93]:
a2_reshaped = np.reshape(a2, (6,1))
a2_reshaped

array([[1. ],
       [2. ],
       [3.3],
       [4. ],
       [5. ],
       [6.5]])

In [95]:
a2_reshaped * a3

ValueError: operands could not be broadcast together with shapes (6,1) (2,3,3) 

In [96]:
a2 /a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [97]:
## floor division (int) div
a2//a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [98]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [99]:
np.log(a2)

array([[0.        , 0.69314718, 1.19392247],
       [1.38629436, 1.60943791, 1.87180218]])

In [100]:
np.std(a2)

1.8226964152656422

In [101]:
np.exp(a2)

array([[  2.71828183,   7.3890561 ,  27.11263892],
       [ 54.59815003, 148.4131591 , 665.14163304]])