# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [10]:
# Create a 1-dimensional NumPy array using np.array()
one_dim = np.arange(1, 10, 3)
one_dim


array([1, 4, 7])

In [9]:
# Create a 2-dimensional NumPy array using np.array()
two_dim = np.random.randint(10, size = (3,4))
two_dim

array([[8, 8, 5, 4],
       [0, 6, 8, 4],
       [8, 9, 8, 6]])

In [12]:
# Create a 3-dimensional Numpy array using np.array()
three_dim = np.random.randint(6, size = (4,3,2))
three_dim

array([[[3, 0],
        [4, 3],
        [1, 0]],

       [[2, 5],
        [4, 3],
        [3, 3]],

       [[4, 1],
        [4, 2],
        [4, 5]],

       [[4, 5],
        [2, 1],
        [2, 2]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [7]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(f"shape{one_dim.shape}, dims:{one_dim.ndim}, dType: {one_dim.dtype}, size: {one_dim.size}")

shape(3,), dims:1, dType: int32, size: 3


In [11]:
# Attributes of 2-dimensional array
print(f"shape{two_dim.shape}, dims:{two_dim.ndim}, dType: {two_dim.dtype}, size: {two_dim.size}")

shape(3, 4), dims:2, dType: int32, size: 12


In [13]:
# Attributes of 3-dimensional array
print(f"shape{three_dim.shape}, dims:{three_dim.ndim}, dType: {three_dim.dtype}, size: {three_dim.size}")

shape(4, 3, 2), dims:3, dType: int32, size: 24


In [14]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

In [15]:
a1 = pd.DataFrame(one_dim)
a1

0
0  1
1  4
2  7

In [16]:
a2 = pd.DataFrame(two_dim)
a2

0  1  2  3
0  8  8  5  4
1  0  6  8  4
2  8  9  8  6

In [19]:
a3 = pd.DataFrame(three_dim.reshape(6,4))
a3

0  1  2  3
0  3  0  4  3
1  1  0  2  5
2  4  3  3  3
3  4  1  4  2
4  4  5  4  5
5  2  1  2  2

In [28]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2), int)
ones

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [29]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3), int)
zeros

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [30]:
# Create an array within a range of 0 and 100 with step 3
range = np.arange(0,101,3)
range

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [31]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand_range = np.random.randint(0, 10, size=(7,2))
rand_range

array([[9, 5],
       [3, 4],
       [3, 8],
       [5, 0],
       [3, 3],
       [0, 9],
       [0, 7]])

In [32]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rand_floats = np.random.uniform(size=(3,5))
rand_floats

array([[0.53078304, 0.55202324, 0.36006966, 0.13028481, 0.30172242],
       [0.90654288, 0.52644474, 0.11320745, 0.83940772, 0.31310096],
       [0.90795899, 0.78246505, 0.92848076, 0.02810975, 0.94955569]])

In [34]:
# Set the random seed to 42
seed = np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random = np.random.randint(0, 11, (4,6), int)
random

array([[ 6,  3, 10,  7,  4,  6],
       [ 9,  2,  6, 10, 10,  7],
       [ 4,  3,  7,  7,  2,  5],
       [ 4,  1,  7,  5,  1,  4]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [37]:
seed = np.random.seed(42)
random = np.random.randint(0, 11, (4,6), int)
random

array([[ 6,  3, 10,  7,  4,  6],
       [ 9,  2,  6, 10, 10,  7],
       [ 4,  3,  7,  7,  2,  5],
       [ 4,  1,  7,  5,  1,  4]])

In [ ]:
The arrays are the same due to the seed being set to the same number.

In [38]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
find_unq = np.random.randint(1, 11, (3,7))
find_unq


array([[ 1, 10,  6,  9,  1, 10,  3],
       [ 7,  4,  9,  3,  5,  3,  7],
       [ 5,  9,  7,  2,  4,  9,  2]])

In [39]:
# Find the unique numbers in the array you just created
np.unique(find_unq)

array([ 1,  2,  3,  4,  5,  6,  7,  9, 10])

In [73]:
# Find the 0'th index of the latest array you created
find_unq[0]

array([ 1, 10,  6,  9,  1, 10,  3])

In [75]:
# Get the first 2 rows of latest array you created
find_unq[:2 :]

array([[ 1, 10,  6,  9,  1, 10,  3],
       [ 7,  4,  9,  3,  5,  3,  7]])

In [76]:
# Get the first 2 values of the first 2 rows of the latest array
find_unq[ :2, :2]

array([[ 1, 10],
       [ 7,  4]])

In [78]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rdrge = np.random.randint(0,11, (3,5))
ones_again = np.ones((3,5), int)

In [79]:
rdrge

array([[5, 5, 9, 3, 5],
       [1, 9, 1, 9, 3],
       [7, 6, 8, 7, 4]])

In [80]:
ones_again

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [81]:
# Add the two arrays together
added = rdrge + ones_again
added

array([[ 6,  6, 10,  4,  6],
       [ 2, 10,  2, 10,  4],
       [ 8,  7,  9,  8,  5]])

In [82]:
# Create another array of ones of shape (5, 3)
another_one = np.ones((5,3), int)
another_one

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [83]:
# Try add the array of ones and the other most recent array together
trying = added + another_one

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [84]:
added.shape

(3, 5)

In [85]:
another_one.shape

(5, 3)

The two arrays have different shapes so they need the same shape. 

In [87]:
added + another_one.T

array([[ 7,  7, 11,  5,  7],
       [ 3, 11,  3, 11,  5],
       [ 9,  8, 10,  9,  6]])

In [88]:
# Create another array of ones of shape (3, 5)
new_one = another_one.T
new_one

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [89]:
# Subtract the new array of ones from the other most recent array
added - new_one

array([[5, 5, 9, 3, 5],
       [1, 9, 1, 9, 3],
       [7, 6, 8, 7, 4]])

In [90]:
# Multiply the ones array with the latest array
added * new_one

array([[ 6,  6, 10,  4,  6],
       [ 2, 10,  2, 10,  4],
       [ 8,  7,  9,  8,  5]])

In [91]:
# Take the latest array to the power of 2 using '**'
added**2

array([[ 36,  36, 100,  16,  36],
       [  4, 100,   4, 100,  16],
       [ 64,  49,  81,  64,  25]])

In [92]:
# Do the same thing with np.square()
np.square(added)

array([[ 36,  36, 100,  16,  36],
       [  4, 100,   4, 100,  16],
       [ 64,  49,  81,  64,  25]])

In [93]:
# Find the mean of the latest array using np.mean()
np.mean(added)

6.466666666666667

In [94]:
# Find the maximum of the latest array using np.max()
np.max(added)

10

In [95]:
# Find the minimum of the latest array using np.min()
np.min(added)

2

In [96]:
# Find the standard deviation of the latest array
np.std(added)

2.6297443897754693

In [97]:
# Find the variance of the latest array
np.var(added)

6.915555555555555

In [98]:
# Reshape the latest array to (3, 5, 1)
added.shape

(3, 5)

In [104]:
added.reshape(3,5,1)



array([[[ 6],
        [ 6],
        [10],
        [ 4],
        [ 6]],

       [[ 2],
        [10],
        [ 2],
        [10],
        [ 4]],

       [[ 8],
        [ 7],
        [ 9],
        [ 8],
        [ 5]]])

In [105]:
# Transpose the latest array
added.T

array([[ 6,  2,  8],
       [ 6, 10,  7],
       [10,  2,  9],
       [ 4, 10,  8],
       [ 6,  4,  5]])

What does the transpose do?

Returns an array with axes transposed.

In [107]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a1a = np.random.randint(0, 11, (3,3))
a2a = np.random.randint(0, 11, (3,2))

In [108]:
a1a

array([[1, 4, 7],
       [9, 8, 8],
       [0, 8, 6]])

In [109]:
a2a

array([[ 8,  7],
       [ 0,  7],
       [ 7, 10]])

In [110]:
# Perform a dot product on the two newest arrays you created
np.dot(a1a, a2a)

array([[ 57, 105],
       [128, 199],
       [ 42, 116]])

In [111]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
onea = np.random.randint(0, 11, (4,3))
oneb = np.random.randint(0, 11, (4,3))

In [112]:
# Perform a dot product on the two newest arrays you created
np.dot(onea, oneb)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [113]:
np.dot(onea, oneb.T)

array([[ 61,  44,  40,  39],
       [ 28,   2,  26,  18],
       [155,  64, 124,  93],
       [164,  54, 131, 115]])

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [114]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
first = np.random.randint(0,10, (2,3))
second = np.random.randint(0,10, (2,3))

In [117]:
first

array([[2, 0, 2],
       [4, 2, 0]])

In [118]:
second

array([[4, 9, 6],
       [6, 8, 9]])

In [119]:
# Compare the two arrays with '>'
first > second

array([[False, False, False],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [116]:
# Compare the two arrays with '>='
first >= second

array([[False, False, False],
       [False, False, False]])

In [120]:
# Find which elements of the first array are greater than 7
first > 7

array([[False, False, False],
       [False, False, False]])

In [121]:
# Which parts of each array are equal? (try using '==')
first == second

array([[False, False, False],
       [False, False, False]])

In [123]:
# Sort one of the arrays you just created in ascending order
np.sort(second)

array([[4, 6, 9],
       [6, 8, 9]])

In [124]:
# Sort the indexes of one of the arrays you just created
np.argsort(second)

array([[0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [125]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(second)

2

In [126]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(first)

1

In [127]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(first, axis=1)

array([0, 0], dtype=int64)

In [128]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(first, axis=0)

array([0, 0, 1], dtype=int64)

In [129]:
# Create an array of normally distributed random numbers
np.random.randn(4, 5)

array([[ 0.08704707, -0.29900735,  0.09176078, -1.98756891, -0.21967189],
       [ 0.35711257,  1.47789404, -0.51827022, -0.8084936 , -0.50175704],
       [ 0.91540212,  0.32875111, -0.5297602 ,  0.51326743,  0.09707755],
       [ 0.96864499, -0.70205309, -0.32766215, -0.39210815, -1.46351495]])

In [134]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.